# Site settings
title: Hassan Iskaf
email: Hiskaf1@gmail.com
url: https://example.github.io
slogan: "'with every click, I develop'"
description: "A creative web developer working with JavaScript, Ruby on Rails, AngularJS and more.."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Hassan Iskaf

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/HassanIskaf
  - title: github
    url: https://github.com/hassanisk
  - title: linkedin
    url: https://www.linkedin.com/in/hassan-iskaf/
# Build settings
markdown: kramdown
permalink: pretty
